import Link from "next/link";

const marketplaceLinks = [{ label: "Vitrine", href: "/" }, { label: "Catálogo", href: "/produtos" }, { label: "Artesãos", href: "/artesoes" }, { label: "Regiões", href: "/artesoes" }, { label: "Técnicas", href: "/produtos" }];
const artisanLinks = [{ label: "Cadastre-se", href: "/cadastro" }, { label: "Painel", href: "/painel-artesao" }, { label: "Adicionar Produto", href: "/painel-artesao" }, { label: "Gestão de Pedidos", href: "/pedidos" }, { label: "Suporte", href: "/login" }];
const institutionalLinks = [{ label: "Sobre o Origem", href: "/" }, { label: "Missão e Valores", href: "/" }, { label: "Imprensa", href: "/" }, { label: "Contato", href: "/login" }, { label: "Privacidade", href: "/" }];

function BrandMark() { return <span className="flex h-8 w-8 items-center justify-center rounded-[2px] bg-[#C1522A]" aria-hidden="true"><svg width="18" height="18" viewBox="0 0 18 18" fill="none"><circle cx="9" cy="9" r="7" stroke="white" strokeWidth="1.5" /><path d="M9 5v4l3 2" stroke="white" strokeWidth="1.5" strokeLinecap="round" /></svg></span>; }
function SocialIcon({ name }: { name: string }) { if (name === "instagram") return <svg width="14" height="14" viewBox="0 0 14 14" fill="none"><rect x="2" y="2" width="10" height="10" rx="3" stroke="currentColor" strokeWidth="1.2" /><circle cx="7" cy="7" r="2.5" stroke="currentColor" strokeWidth="1.2" /></svg>; if (name === "facebook") return <svg width="14" height="14" viewBox="0 0 14 14" fill="currentColor"><path d="M8 12V7.8h1.5l.2-1.6H8V5.2c0-.5.1-.8.8-.8h1V3a11 11 0 0 0-1.2-.1c-1.3 0-2.2.8-2.2 2.2v1.1H5v1.6h1.4V12H8Z" /></svg>; return <svg width="14" height="14" viewBox="0 0 14 14" fill="currentColor"><path d="M11.8 4.1a2.7 2.7 0 0 1-.8.2 1.4 1.4 0 0 0 .6-.8 2.8 2.8 0 0 1-.9.3 1.4 1.4 0 0 0-2.4 1c0 .1 0 .2.1.3A4 4 0 0 1 5.5 3a1.4 1.4 0 0 0 .4 1.9 1.4 1.4 0 0 1-.6-.2c0 .7.5 1.3 1.2 1.4a1.4 1.4 0 0 1-.6 0c.2.6.8 1 1.5 1A2.8 2.8 0 0 1 3.8 8a4 4 0 0 0 6.2-3.4v-.2c.3-.2.6-.5.8-.8Z" /></svg>; }

function LinkColumn({ title, links }: { title: string; links: { label: string; href: string }[] }) { return <div><p className="mb-4 text-[.7rem] font-bold uppercase tracking-[.12em] text-[#C1522A]">{title}</p>{links.map((link) => <Link key={`${title}-${link.label}`} href={link.href} className="mb-2 block text-sm text-white/60 hover:text-white">{link.label}</Link>)}</div>; }

export default function Footer() { return <footer className="bg-[#1B4332] text-white"><div className="mx-auto max-w-[1440px] px-6 py-16"><div className="grid gap-10 md:grid-cols-[2fr_1fr_1fr_1fr]"><div className="max-w-[380px]"><Link href="/" className="mb-4 flex items-center gap-2"><BrandMark /><span className="font-display text-xl font-semibold">Origem</span></Link><p className="max-w-[320px] text-[.9rem] leading-[1.7] text-white/65">Marketplace dedicado ao artesanato e à economia criativa de Pernambuco. Conectamos artesãos autênticos a quem valoriza a cultura nordestina.</p><div className="mt-5 flex gap-3">{["instagram", "facebook", "twitter"].map((network) => <a key={network} href="#" aria-label={network} className="flex h-9 w-9 items-center justify-center rounded-sm border border-white/20 text-white hover:border-[#C1522A] hover:text-[#C1522A]"><SocialIcon name={network} /></a>)}</div></div><LinkColumn title="Marketplace" links={marketplaceLinks} /><LinkColumn title="Artesão" links={artisanLinks} /><LinkColumn title="Institucional" links={institutionalLinks} /></div><div className="mt-12 flex flex-wrap items-center justify-between gap-4 border-t border-white/10 pt-6"><p className="text-[.8125rem] text-white/40">© 2026 Origem — Artesanato Pernambucano. Todos os direitos reservados.</p><span className="text-xs tracking-[.06em] text-white/35">FEITO COM AMOR EM RECIFE, PE</span></div></div></footer>; }
